=== dalleraro/DP2_Assignment_1/src/dtd/wfInfo.dtd
<!-- DTD describing a workflow -->
<!ELEMENT workflow (action*)>
<!ATTLIST workflow
        name            ID          #REQUIRED
>
<!ELEMENT action (simple_action|process_action) >
<!ATTLIST action
        name            ID          #REQUIRED
        role            NMTOKEN     #REQUIRED
        AutomIst        (yes|no)    "no"
>
<!ELEMENT simple_action EMPTY >
<!ATTLIST simple_action
        nexPossActions  IDREFS      #IMPLIED
>
<!ELEMENT process_action EMPTY >
<!ATTLIST process_action
        workflow        IDREF       #REQUIRED
>

=== dalleraro/DP2_Assignment_1/src/dtd/wfInfo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE workflow SYSTEM "wfinfo.dtd" >

<workflow name="article_production">
    <action name="Writing" role="Journalist" AutomIst="true">
        <simple_action nexPossActions="Checking"></simple_action>
    </action>
    <action name="Checking" role="Editor">
        <simple_action nexPossActions="Revising Publication"></simple_action>
    </action>
    <action name="Revising" role="Journalist">
        <simple_action nexPossActions="Checking"></simple_action>
    </action>
    <action name="Publication" role="Editor">
        <simple_action></simple_action>
    </action>
</workflow>
